# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - 'size' refers to the length of the shared border between solid black and solid white rectangle.
#   See README.md or https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#pose-estimation for details.
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
    {
      name: 'my_bundle',
      layout:
        [
          # {id: 0, size: 0.129, x: 3.0000, y: 3.0000, z: 0.0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          # {id: 1, size: 0.129, x: 4.5000, y: 3.0000, z: 0.0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          # {id: 2, size: 0.129, x: 6.0000, y: 3.0000, z: 0.0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          # {id: 3, size: 0.129, x: 7.5000, y: 3.0000, z: 0.0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          # {id: 4, size: 0.129, x: 9.0000, y: 3.0000, z: 0.0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          # {id: 5, size: 0.129, x: 10.5000, y: 3.0000, z: 0.0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          # {id: 6, size: 0.129, x: 12.0000, y: 3.0000, z: 0.0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          
          {id: 0, size: 0.129, x: 5.1000, y: 5.1000, z: 0.0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          {id: 1, size: 0.129, x: 6.6000, y: 5.1000, z: 0.0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          {id: 2, size: 0.129, x: 8.1000, y: 5.1000, z: 0.0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          {id: 3, size: 0.129, x: 9.6000, y: 5.1000, z: 0.0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          {id: 4, size: 0.129, x: 9.6000, y: 6.3000, z: 0.0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          {id: 5, size: 0.129, x: 9.6000, y: 7.5000, z: 0.0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          {id: 6, size: 0.129, x: 9.6000, y: 8.7000, z: 0.0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          {id: 7, size: 0.129, x: 9.6000, y: 9.9000, z: 0.0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          {id: 8, size: 0.129, x: 8.1000, y: 9.9000, z: 0.0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          {id: 9, size: 0.129, x: 6.6000, y: 9.9000, z: 0.0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          {id: 10, size: 0.129, x: 5.1000, y: 9.9000, z: 0.0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          {id: 11, size: 0.129, x: 3.6000, y: 9.9000, z: 0.0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          {id: 12, size: 0.129, x: 2.1000, y: 9.9000, z: 0.0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          {id: 13, size: 0.129, x: 2.1000, y: 8.7000, z: 0.0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          {id: 14, size: 0.129, x: 2.1000, y: 7.5000, z: 0.0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          {id: 15, size: 0.129, x: 2.1000, y: 6.3000, z: 0.0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          {id: 16, size: 0.129, x: 2.1000, y: 5.1000, z: 0.0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
          {id: 17, size: 0.129, x: 3.0000, y: 5.1000, z: 0.0, qw: 0.707, qx: 0.0, qy: 0.0, qz: -0.707},
        ]
    }
  ]
